/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_ap_spare_regs_regs.h
 *
 * @brief ap_spare_regs registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: d29df7cb4856df436f62d3ee3bde63b0
 *
 * JSON: AP_SPARE_REGS.json
 *
 */

#ifndef __AL_HAL_AP_SPARE_REGS_REGS_H__
#define __AL_HAL_AP_SPARE_REGS_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_ap_spare_regs_reg_ones
 *
 * 64 bits of default ones
 **************************************************************************************************/
struct al_ap_spare_regs_reg_ones {
	/* [0x0] */
	uint32_t ones;
};

/**** ones register ****/
/*
 * all ones
 * Reset: 0xffffffff  Access: RW
 */
#define AP_SPARE_REGS_REG_ONES_ONES_VALUE_MASK 0xFFFFFFFF
#define AP_SPARE_REGS_REG_ONES_ONES_VALUE_SHIFT 0

/**************************************************************************************************
 * al_ap_spare_regs_reg_zeros
 *
 * 64 bits of default zeros
 **************************************************************************************************/
struct al_ap_spare_regs_reg_zeros {
	/* [0x0] */
	uint32_t zeros;
};

/**** zeros register ****/
/*
 * all zeros
 * Reset: 0x0         Access: RW
 */
#define AP_SPARE_REGS_REG_ZEROS_ZEROS_VALUE_MASK 0xFFFFFFFF
#define AP_SPARE_REGS_REG_ZEROS_ZEROS_VALUE_SHIFT 0

/**************************************************************************************************
 * al_ap_spare_regs_regs
 *
 * 128 bits for ECOs (64 ones and 64 zeros)
 **************************************************************************************************/
struct al_ap_spare_regs_regs {
	/* [0x0] 64 bits of default ones */
	struct al_ap_spare_regs_reg_ones reg_ones[2];
	/* [0x8] */
	uint32_t rsrvd_0[2];
	/* [0x10] 64 bits of default zeros */
	struct al_ap_spare_regs_reg_zeros reg_zeros[2];
	/* [0x18] */
	uint32_t rsrvd_1[2];
};

#ifdef __cplusplus
}
#endif

#endif

/** @} */
