/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_cell_fe_size_regs.h
 *
 * @brief cell_fe_size registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: b20adce6ad7267f353e77eade684d8fc
 *
 * JSON: AP_FE_SIZE.json
 *
 */

#ifndef __AL_HAL_CELL_FE_SIZE_REGS_H__
#define __AL_HAL_CELL_FE_SIZE_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_cell_fe_size_regs
 **************************************************************************************************/
struct al_cell_fe_size_regs {
	/* [0x0] offset for the field extract (from the MSB) */
	uint32_t offset;
	/*
	 * [0x4] FE size - Create mask on FE output  0 - Means full bus (no mask) n - use n lsb bits
	 * of FE value
	 */
	uint32_t size;
};

/**** offset register ****/
/* Reset: 0x0         Access: RW */
#define CELL_FE_SIZE_OFFSET_VAL_MASK     0x000003FF
#define CELL_FE_SIZE_OFFSET_VAL_SHIFT    0

/**** size register ****/
/* Reset: 0x0         Access: RW */
#define CELL_FE_SIZE_SIZE_VAL_MASK       0x0000000F
#define CELL_FE_SIZE_SIZE_VAL_SHIFT      0

#ifdef __cplusplus
}
#endif

#endif

/** @} */
