/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_cell_bw_limiter_regs.h
 *
 * @brief cell_bw_limiter registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: 43f1cf6a9c71df63777fdbb458e9e70e
 *
 * JSON: AP_BW_LIMITER.json
 *
 */

#ifndef __AL_HAL_CELL_BW_LIMITER_REGS_H__
#define __AL_HAL_CELL_BW_LIMITER_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_cell_bw_limiter_regs
 *
 * AP_BW_LIMITER configurations
 **************************************************************************************************/
struct al_cell_bw_limiter_regs {
	/* [0x0] number of allowed transactions out of <cfg_num_cycles>. */
	uint32_t allowed_num_trns;
	/* [0x4] period for examination. 0 means do nothing */
	uint32_t num_cycles;
};

/**** allowed_num_trns register ****/
/* Reset: 0x8         Access: RW */
#define CELL_BW_LIMITER_ALLOWED_NUM_TRNS_VAL_MASK 0x000000FF
#define CELL_BW_LIMITER_ALLOWED_NUM_TRNS_VAL_SHIFT 0

/**** num_cycles register ****/
/* Reset: 0x8         Access: RW */
#define CELL_BW_LIMITER_NUM_CYCLES_VAL_MASK 0x000000FF
#define CELL_BW_LIMITER_NUM_CYCLES_VAL_SHIFT 0

#ifdef __cplusplus
}
#endif

#endif

/** @} */
