/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_cell_afifo_thr_regs.h
 *
 * @brief cell_afifo_thr registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: d266646ca4552cf70fbc690655d415d0
 *
 * JSON: AP_ASYNC_FIFO_THRESHOLD.json
 *
 */

#ifndef __AL_HAL_CELL_AFIFO_THR_REGS_H__
#define __AL_HAL_CELL_AFIFO_THR_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_cell_afifo_thr_regs
 *
 * AP_ASYNC_FIFO_THRESHOLD configurations
 **************************************************************************************************/
struct al_cell_afifo_thr_regs {
	/* [0x0] push_x & pop_y enable */
	uint32_t fifo_enable;
	/* [0x4] fifo threshold */
	uint32_t fifo_threshold;
};

/**** fifo_enable register ****/
/*
 * enable push_x side
 * Reset: 0x1         Access: RW
 */
#define CELL_AFIFO_THR_FIFO_ENABLE_X_SIDE (1 << 0)
#define CELL_AFIFO_THR_FIFO_ENABLE_X_SIDE_MASK 0x00000001
#define CELL_AFIFO_THR_FIFO_ENABLE_X_SIDE_SHIFT 0
/*
 * enable pop_y side
 * Reset: 0x1         Access: RW
 */
#define CELL_AFIFO_THR_FIFO_ENABLE_Y_SIDE (1 << 1)
#define CELL_AFIFO_THR_FIFO_ENABLE_Y_SIDE_MASK 0x00000002
#define CELL_AFIFO_THR_FIFO_ENABLE_Y_SIDE_SHIFT 1

/**** fifo_threshold register ****/
/* Reset: 0x10        Access: RW */
#define CELL_AFIFO_THR_FIFO_THRESHOLD_VAL_MASK 0x0000003F
#define CELL_AFIFO_THR_FIFO_THRESHOLD_VAL_SHIFT 0

#ifdef __cplusplus
}
#endif

#endif

/** @} */
