/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_ap_debug_fsm_regs.h
 *
 * @brief ap_debug_fsm registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: 683e2025096b2dbda0dbba9415f743a2
 *
 * JSON: AP_DEBUG_FSM.json
 *
 */

#ifndef __AL_HAL_AP_DEBUG_FSM_REGS_H__
#define __AL_HAL_AP_DEBUG_FSM_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_ap_debug_fsm_fsm
 *
 * register to debug FSM
 **************************************************************************************************/
struct al_ap_debug_fsm_fsm {
	/* [0x0] */
	uint32_t debug;
};

/**** debug register ****/
/*
 * current state read from the FSM
 * Reset: 0x0         Access: RO
 */
#define AP_DEBUG_FSM_FSM_DEBUG_CURRENT_STATE_MASK 0x0000FFFF
#define AP_DEBUG_FSM_FSM_DEBUG_CURRENT_STATE_SHIFT 0
/*
 * bad FSM state was observed (latched until reset)
 * Reset: 0x0         Access: RO
 */
#define AP_DEBUG_FSM_FSM_DEBUG_BAD_STATE_LATCHED (1 << 30)
#define AP_DEBUG_FSM_FSM_DEBUG_BAD_STATE_LATCHED_MASK 0x40000000
#define AP_DEBUG_FSM_FSM_DEBUG_BAD_STATE_LATCHED_SHIFT 30
/*
 * SW reset to FSM
 * Reset: 0x0         Access: WO
 */
#define AP_DEBUG_FSM_FSM_DEBUG_RESET_FSM (1 << 31)
#define AP_DEBUG_FSM_FSM_DEBUG_RESET_FSM_MASK 0x80000000
#define AP_DEBUG_FSM_FSM_DEBUG_RESET_FSM_SHIFT 31

/**************************************************************************************************
 * al_ap_debug_fsm_regs
 *
 * FSM debug register
 **************************************************************************************************/
struct al_ap_debug_fsm_regs {
	/* [0x0] register to debug FSM */
	struct al_ap_debug_fsm_fsm fsm;
	/* [0x4] */
	uint32_t rsrvd_0[3];
};

#ifdef __cplusplus
}
#endif

#endif

/** @} */
