/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_cell_fe_fm_regs.h
 *
 * @brief cell_fe_fm registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: eb2ed81da8e911cf811a81b43a9c0131
 *
 * JSON: AP_FE_FM.json
 *
 */

#ifndef __AL_HAL_CELL_FE_FM_REGS_H__
#define __AL_HAL_CELL_FE_FM_REGS_H__

#include "al_hal_common.h"

#include "al_hal_cell_fe_regs.h"
#include "al_hal_cell_fm_regs.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_cell_fe_fm_regs
 **************************************************************************************************/
struct al_cell_fe_fm_regs {
	/* [0x0] Field extract */
	struct al_cell_fe_regs fe;
	/* [0x4] Field merge */
	struct al_cell_fm_regs fm;
};

/* Asserts */
al_static_assert(sizeof(struct al_cell_fe_regs) == 4,
	"Expected other registers struct size!");
al_static_assert(sizeof(struct al_cell_fm_regs) == 8,
	"Expected other registers struct size!");

#ifdef __cplusplus
}
#endif

#endif

/** @} */
