/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_table_protection_regs.h
 *
 * @brief table_protection registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: bd76732212be6ffb349331bb386941f6
 *
 * JSON: table_protection.json
 *
 */

#ifndef __AL_HAL_TABLE_PROTECTION_REGS_H__
#define __AL_HAL_TABLE_PROTECTION_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_table_protection_cfg_access_area
 *
 * opsel vector
 **************************************************************************************************/
struct al_table_protection_cfg_access_area {
	/* [0x0] Base table address for CPU access */
	uint32_t base;
	/* [0x4] Section size for CPU access */
	uint32_t size;
};

/**** base register ****/
/*
 * :
 * Reset: 0x0         Access: RW
 */
#define TABLE_PROTECTION_CFG_ACCESS_AREA_BASE_VAL_MASK 0x000007FF
#define TABLE_PROTECTION_CFG_ACCESS_AREA_BASE_VAL_SHIFT 0

/**** size register ****/
/* Reset: 0x0         Access: RW */
#define TABLE_PROTECTION_CFG_ACCESS_AREA_SIZE_VAL_MASK 0x00000FFF
#define TABLE_PROTECTION_CFG_ACCESS_AREA_SIZE_VAL_SHIFT 0

/**************************************************************************************************
 * al_table_protection_cfg
 *
 * table protection parameters
 **************************************************************************************************/
struct al_table_protection_cfg {
	/* [0x0] opsel vector */
	struct al_table_protection_cfg_access_area access_area[16];
	/* [0x80] Enable SW access protection */
	uint32_t protection_sel;
};

/**** protection_sel register ****/
/* Reset: 0x0         Access: RW */
#define TABLE_PROTECTION_CFG_PROTECTION_SEL_EN (1 << 0)
#define TABLE_PROTECTION_CFG_PROTECTION_SEL_EN_MASK 0x00000001
#define TABLE_PROTECTION_CFG_PROTECTION_SEL_EN_SHIFT 0

/**************************************************************************************************
 * al_table_protection_regs
 **************************************************************************************************/
struct al_table_protection_regs {
	/* [0x0] table protection parameters */
	struct al_table_protection_cfg cfg;
	/* [0x84] */
	uint32_t rsrvd_0[31];
};

#ifdef __cplusplus
}
#endif

#endif

/** @} */
