/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_cell_fm_regs.h
 *
 * @brief cell_fm registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: ecea1f08e2f8086a85db2fc6ca0430ef
 *
 * JSON: AP_FM.json
 *
 */

#ifndef __AL_HAL_CELL_FM_REGS_H__
#define __AL_HAL_CELL_FM_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_cell_fm_regs
 **************************************************************************************************/
struct al_cell_fm_regs {
	/* [0x0] offset for the field merge (from the MSB) */
	uint32_t offset;
	/* [0x4] size for the field merge (from the MSB) */
	uint32_t size;
};

/**** offset register ****/
/*
 * offset value
 * Reset: 0x0         Access: RW
 */
#define CELL_FM_OFFSET_VAL_MASK          0x000003FF
#define CELL_FM_OFFSET_VAL_SHIFT         0

/**** size register ****/
/*
 * size value
 * Reset: 0x0         Access: RW
 */
#define CELL_FM_SIZE_VAL_MASK            0x000007FF
#define CELL_FM_SIZE_VAL_SHIFT           0

#ifdef __cplusplus
}
#endif

#endif

/** @} */
