/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_cell_fe_regs.h
 *
 * @brief cell_fe registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: b752e66933aca267eafb1a31d6dcc242
 *
 * JSON: AP_FE.json
 *
 */

#ifndef __AL_HAL_CELL_FE_REGS_H__
#define __AL_HAL_CELL_FE_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_cell_fe_regs
 **************************************************************************************************/
struct al_cell_fe_regs {
	/* [0x0] offset for the field extract (from the MSB) */
	uint32_t offset;
};

/**** offset register ****/
/* Reset: 0x0         Access: RW */
#define CELL_FE_OFFSET_VAL_MASK          0x000003FF
#define CELL_FE_OFFSET_VAL_SHIFT         0

#ifdef __cplusplus
}
#endif

#endif

/** @} */
