/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_cell_alu_x3_regs.h
 *
 * @brief cell_alu_x3 registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: 7285b06577e9114161a0ee60591ad1a5
 *
 * JSON: AP_ALU_EXTEND.json
 *
 */

#ifndef __AL_HAL_CELL_ALU_X3_REGS_H__
#define __AL_HAL_CELL_ALU_X3_REGS_H__

#include "al_hal_common.h"

#include "al_hal_cell_alu_regs.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_cell_alu_x3_regs
 **************************************************************************************************/
struct al_cell_alu_x3_regs {
	/* [0x0] first level ALUs */
	struct al_cell_alu_regs first[2];
	/* [0x40] second level ALU */
	struct al_cell_alu_regs second;
};

/* Asserts */
al_static_assert(sizeof(struct al_cell_alu_regs) == 32,
	"Expected other registers struct size!");

#ifdef __cplusplus
}
#endif

#endif

/** @} */
