/*
 * Copyright 2019, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_ap_mem_wrap_regs.h
 *
 * @brief ap_mem_wrap registers
 *
 * This file was auto-generated by RegGen v1.3.13
 *
 * Hash Key is: f5587c20b48ed47beb359f4f680e852a
 *
 * JSON: AP_MEM_WRAP.json
 *
 */

#ifndef __AL_HAL_AP_MEM_WRAP_REGS_H__
#define __AL_HAL_AP_MEM_WRAP_REGS_H__

#include "al_hal_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_ap_mem_wrap_regs
 *
 * anpa_mem_wrap_regs
 **************************************************************************************************/
struct al_ap_mem_wrap_regs {
	/* [0x0] memory info */
	uint32_t info;
	/* [0x4] memory configuration */
	uint32_t cfg;
	/* [0x8] memory status */
	uint32_t status;
	/* [0xc] single error detection */
	uint32_t err_counter;
	/* [0x10] single error threshold */
	uint32_t err_threshold;
	/* [0x14] */
	uint32_t rsrvd_0[3];
};

/**** info register ****/
/*
 * Shut_Down
 * Reset: 0x0         Access: RO, RreturnsRst
 */
#define AP_MEM_WRAP_INFO_SD_EN           (1 << 0)
#define AP_MEM_WRAP_INFO_SD_EN_MASK      0x00000001
#define AP_MEM_WRAP_INFO_SD_EN_SHIFT     0
/*
 * Initialization
 * Reset: 0x0         Access: RO, RreturnsRst
 */
#define AP_MEM_WRAP_INFO_INIT_EN         (1 << 1)
#define AP_MEM_WRAP_INFO_INIT_EN_MASK    0x00000002
#define AP_MEM_WRAP_INFO_INIT_EN_SHIFT   1
/*
 * Single_Error_Detection
 * Reset: 0x0         Access: RO, RreturnsRst
 */
#define AP_MEM_WRAP_INFO_SED_EN          (1 << 2)
#define AP_MEM_WRAP_INFO_SED_EN_MASK     0x00000004
#define AP_MEM_WRAP_INFO_SED_EN_SHIFT    2
/*
 * Double_Error_Detection
 * Reset: 0x0         Access: RO, RreturnsRst
 */
#define AP_MEM_WRAP_INFO_DED_EN          (1 << 3)
#define AP_MEM_WRAP_INFO_DED_EN_MASK     0x00000008
#define AP_MEM_WRAP_INFO_DED_EN_SHIFT    3
/*
 * Single_Error_Correction
 * Reset: 0x0         Access: RO, RreturnsRst
 */
#define AP_MEM_WRAP_INFO_SEC_EN          (1 << 4)
#define AP_MEM_WRAP_INFO_SEC_EN_MASK     0x00000010
#define AP_MEM_WRAP_INFO_SEC_EN_SHIFT    4
/*
 * Force_Error_Detection
 * Reset: 0x0         Access: RO, RreturnsRst
 */
#define AP_MEM_WRAP_INFO_FED_EN          (1 << 5)
#define AP_MEM_WRAP_INFO_FED_EN_MASK     0x00000020
#define AP_MEM_WRAP_INFO_FED_EN_SHIFT    5
/*
 * Write_Mask
 * Reset: 0x0         Access: RO, RreturnsRst
 */
#define AP_MEM_WRAP_INFO_WM_EN           (1 << 6)
#define AP_MEM_WRAP_INFO_WM_EN_MASK      0x00000040
#define AP_MEM_WRAP_INFO_WM_EN_SHIFT     6

/**** cfg register ****/
/*
 * Shut Down
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_SD               (1 << 0)
#define AP_MEM_WRAP_CFG_SD_MASK          0x00000001
#define AP_MEM_WRAP_CFG_SD_SHIFT         0
/*
 * initialization trigger
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_INIT_TRIG        (1 << 1)
#define AP_MEM_WRAP_CFG_INIT_TRIG_MASK   0x00000002
#define AP_MEM_WRAP_CFG_INIT_TRIG_SHIFT  1
/*
 * Reserved
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_RSRVD_ECC_MASK   0x0000000C
#define AP_MEM_WRAP_CFG_RSRVD_ECC_SHIFT  2
/*
 * Single Error Injection
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_SEI              (1 << 4)
#define AP_MEM_WRAP_CFG_SEI_MASK         0x00000010
#define AP_MEM_WRAP_CFG_SEI_SHIFT        4
/*
 * Double Error Injection
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_DEI              (1 << 5)
#define AP_MEM_WRAP_CFG_DEI_MASK         0x00000020
#define AP_MEM_WRAP_CFG_DEI_SHIFT        5
/*
 * Force Error Detection
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_FED              (1 << 6)
#define AP_MEM_WRAP_CFG_FED_MASK         0x00000040
#define AP_MEM_WRAP_CFG_FED_SHIFT        6
/*
 * ECC Bypass
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_ECC_BYPASS       (1 << 7)
#define AP_MEM_WRAP_CFG_ECC_BYPASS_MASK  0x00000080
#define AP_MEM_WRAP_CFG_ECC_BYPASS_SHIFT 7
/*
 * Error Injection width
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_ERR_INJ_WIDTH_MASK 0x00000F00
#define AP_MEM_WRAP_CFG_ERR_INJ_WIDTH_SHIFT 8
/*
 * Clear read error indication
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_READ_ERR_CLEAR   (1 << 12)
#define AP_MEM_WRAP_CFG_READ_ERR_CLEAR_MASK 0x00001000
#define AP_MEM_WRAP_CFG_READ_ERR_CLEAR_SHIFT 12
/*
 * Clear single error counter
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_COR_ERR_CNT_CLEAR (1 << 13)
#define AP_MEM_WRAP_CFG_COR_ERR_CNT_CLEAR_MASK 0x00002000
#define AP_MEM_WRAP_CFG_COR_ERR_CNT_CLEAR_SHIFT 13
/*
 * Clear double error counter
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_UNCOR_ERR_CNT_CLEAR (1 << 14)
#define AP_MEM_WRAP_CFG_UNCOR_ERR_CNT_CLEAR_MASK 0x00004000
#define AP_MEM_WRAP_CFG_UNCOR_ERR_CNT_CLEAR_SHIFT 14
/*
 * Reserved
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_RSRVD_SMS        (1 << 15)
#define AP_MEM_WRAP_CFG_RSRVD_SMS_MASK   0x00008000
#define AP_MEM_WRAP_CFG_RSRVD_SMS_SHIFT  15
/*
 * Read Margin Enable
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_RME              (1 << 16)
#define AP_MEM_WRAP_CFG_RME_MASK         0x00010000
#define AP_MEM_WRAP_CFG_RME_SHIFT        16
/*
 * Read Margin
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_RM_MASK          0x001E0000
#define AP_MEM_WRAP_CFG_RM_SHIFT         17
/*
 * Read Margin Enable PortB
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_RMEB             (1 << 21)
#define AP_MEM_WRAP_CFG_RMEB_MASK        0x00200000
#define AP_MEM_WRAP_CFG_RMEB_SHIFT       21
/*
 * Read Margin PortB
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_RMB_MASK         0x03C00000
#define AP_MEM_WRAP_CFG_RMB_SHIFT        22
/*
 * TEST1
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_TEST1            (1 << 26)
#define AP_MEM_WRAP_CFG_TEST1_MASK       0x04000000
#define AP_MEM_WRAP_CFG_TEST1_SHIFT      26
/*
 * TEST1 PortB
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_TEST1B           (1 << 27)
#define AP_MEM_WRAP_CFG_TEST1B_MASK      0x08000000
#define AP_MEM_WRAP_CFG_TEST1B_SHIFT     27
/*
 * TEST Read_Write Margin
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_TESTRWM          (1 << 28)
#define AP_MEM_WRAP_CFG_TESTRWM_MASK     0x10000000
#define AP_MEM_WRAP_CFG_TESTRWM_SHIFT    28
/*
 * TEST_RNM
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_TESTRNM          (1 << 29)
#define AP_MEM_WRAP_CFG_TESTRNM_MASK     0x20000000
#define AP_MEM_WRAP_CFG_TESTRNM_SHIFT    29
/*
 * Reserved
 * Reset: 0x0         Access: RW
 */
#define AP_MEM_WRAP_CFG_RSRVD_MEM_MASK   0xC0000000
#define AP_MEM_WRAP_CFG_RSRVD_MEM_SHIFT  30

/**** status register ****/
/*
 * Ready for Operation
 * Reset: 0x0         Access: RO
 */
#define AP_MEM_WRAP_STATUS_ROP           (1 << 0)
#define AP_MEM_WRAP_STATUS_ROP_MASK      0x00000001
#define AP_MEM_WRAP_STATUS_ROP_SHIFT     0
/*
 * Init In Progress
 * Reset: 0x0         Access: RO
 */
#define AP_MEM_WRAP_STATUS_INIT_IN_PROGRESS (1 << 1)
#define AP_MEM_WRAP_STATUS_INIT_IN_PROGRESS_MASK 0x00000002
#define AP_MEM_WRAP_STATUS_INIT_IN_PROGRESS_SHIFT 1
/* Reset: 0x0         Access: RO */
#define AP_MEM_WRAP_STATUS_RSRVD_MEM_MASK 0x000000FC
#define AP_MEM_WRAP_STATUS_RSRVD_MEM_SHIFT 2
/*
 * Soft Error Detection
 * Reset: 0x0         Access: RO
 */
#define AP_MEM_WRAP_STATUS_READ_ERR      (1 << 8)
#define AP_MEM_WRAP_STATUS_READ_ERR_MASK 0x00000100
#define AP_MEM_WRAP_STATUS_READ_ERR_SHIFT 8
/*
 * Soft Error Correction
 * Reset: 0x0         Access: RO
 */
#define AP_MEM_WRAP_STATUS_SEC           (1 << 9)
#define AP_MEM_WRAP_STATUS_SEC_MASK      0x00000200
#define AP_MEM_WRAP_STATUS_SEC_SHIFT     9
/*
 * Address Fail
 * Reset: 0x0         Access: RO
 */
#define AP_MEM_WRAP_STATUS_ADDR_FAIL_MASK 0xFFFF0000
#define AP_MEM_WRAP_STATUS_ADDR_FAIL_SHIFT 16

/**** err_counter register ****/
/* Reset: 0x0         Access: RO */
#define AP_MEM_WRAP_ERR_COUNTER_CORRECTED_MASK 0x0000FFFF
#define AP_MEM_WRAP_ERR_COUNTER_CORRECTED_SHIFT 0
/* Reset: 0x0         Access: RO */
#define AP_MEM_WRAP_ERR_COUNTER_UNCORRECTED_MASK 0xFFFF0000
#define AP_MEM_WRAP_ERR_COUNTER_UNCORRECTED_SHIFT 16

/**** err_threshold register ****/
/* Reset: 0xffff      Access: RW */
#define AP_MEM_WRAP_ERR_THRESHOLD_CORRECTED_MASK 0x0000FFFF
#define AP_MEM_WRAP_ERR_THRESHOLD_CORRECTED_SHIFT 0

#ifdef __cplusplus
}
#endif

#endif

/** @} */
