#define __KSYM___bitmap_and		1
#define __KSYM___ioremap		1
#define __KSYM___iounmap		1
#define __KSYM___ip_select_ident	1
#define __KSYM___nf_conntrack_find	1
#define __KSYM___release_region		1
#define __KSYM___request_region		1
#define __KSYM___skb_pad		1
#define __KSYM___sw_hweight64		1
#define __KSYM___tasklet_hi_schedule	1
#define __KSYM__dma_cache_inv		1
#define __KSYM__dma_cache_wback_inv	1
#define __KSYM_bus_find_device		1
#define __KSYM_connlimit_destroy_conntrack	1
#define __KSYM_console_drivers		1
#define __KSYM_console_printk		1
#define __KSYM_crc32_le			1
#define __KSYM_crypto_req_done		1
#define __KSYM_dev_alloc_name		1
#define __KSYM_dev_alloc_name		1
#define __KSYM_dev_disable_change	1
#define __KSYM_dev_lockless_classify	1
#define __KSYM_netdev_walk_all_lower_dev_rcu	1
#define __KSYM_device_match_name	1
#define __KSYM_devm_gpio_request	1
#define __KSYM_enable_irq		1
#define __KSYM_ethtool_convert_legacy_u32_to_link_mode	1
#define __KSYM_fp_nf_changed		1
#define __KSYM_fp_ptype_all_changed	1
#define __KSYM_fp_xfrm_changed		1
#define __KSYM_get_mtd_device		1
#define __KSYM_get_mtd_device_nm	1
#define __KSYM_get_some_log		1
#define __KSYM_gpio_free		1
#define __KSYM_gpio_request		1
#define __KSYM_gpio_to_desc		1
#define __KSYM_gpiod_add_lookup_table	1
#define __KSYM_gpiod_direction_input	1
#define __KSYM_gpiod_direction_output_raw	1
#define __KSYM_gpiod_get_raw_value	1
#define __KSYM_gpiod_set_raw_value	1
#define __KSYM_gro_normal_list		1
#define __KSYM_hrtimer_forward		1
#define __KSYM_hrtimer_try_to_cancel	1
#define __KSYM_hwmon_device_register	1
#define __KSYM_hwmon_device_register_with_info	1
#define __KSYM_hwmon_device_unregister	1
#define __KSYM_i2c_get_adapter		1
#define __KSYM_i2c_put_adapter		1
#define __KSYM_i2c_smbus_read_i2c_block_data	1
#define __KSYM_i2c_smbus_write_i2c_block_data	1
#define __KSYM_i2c_transfer_buffer_flags	1
#define __KSYM_iomem_resource		1
#define __KSYM_ip_forward		1
#define __KSYM_ip_local_deliver		1
#define __KSYM_is_ar7240		1
#define __KSYM_is_crs_type		1
#define __KSYM_is_honeybee		1
#define __KSYM_is_music_lite		1
#define __KSYM_is_scorpion		1
#define __KSYM_is_wasp			1
#define __KSYM_ksize			1
#define __KSYM_kstrtou16		1
#define __KSYM_kstrtoull		1
#define __KSYM_ktime_get_ts64		1
#define __KSYM_led_classdev_register_ext	1
#define __KSYM_led_classdev_register_ext	1
#define __KSYM_led_classdev_unregister	1
#define __KSYM_led_classdev_unregister	1
#define __KSYM_lzo1x_decompress_safe	1
#define __KSYM_mips_hpt_frequency	1
#define __KSYM_mips_mac_address		1
#define __KSYM_mips_machtype		1
#define __KSYM_mips_machgroup		1
#define __KSYM_mtd_block_isbad		1
#define __KSYM_mtd_block_markbad	1
#define __KSYM_mtd_erase		1
#define __KSYM_mtd_read			1
#define __KSYM_mtd_read_fact_prot_reg	1
#define __KSYM_mtd_read_oob		1
#define __KSYM_mtd_write		1
#define __KSYM_mtd_write_oob		1
#define __KSYM_napi_gro_flush		1
#define __KSYM_netdev_pick_tx		1
#define __KSYM_netdev_core_pick_tx		1
#define __KSYM_netif_schedule_queue	1
#define __KSYM_nf_conntrack_change_ip	1
#define __KSYM_ns_to_timespec64		1
#define __KSYM_of_get_named_gpio_flags	1
#define __KSYM_of_machine_is_compatible	1
#define __KSYM_on_each_cpu		1
#define __KSYM_pci_read_config_byte	1
#define __KSYM_pci_read_config_dword	1
#define __KSYM_pci_write_config_byte	1
#define __KSYM_pci_write_config_dword	1
#define __KSYM_per_cpu_last_rx_dev	1
#define __KSYM_per_cpu_port		1
#define __KSYM_per_cpu_xmit_switched	1
#define __KSYM_platform_bus_type	1
#define __KSYM_platform_device_register	1
#define __KSYM_platform_device_register_full	1
#define __KSYM_platform_device_unregister	1
#define __KSYM_policy_routing		1
#define __KSYM_ppp_get_device		1
#define __KSYM_ppp_get_stats		1
#define __KSYM_ppp_net_ioctl		1
#define __KSYM_ppp_start_xmit		1
#define __KSYM_pppoe_chan_ops		1
#define __KSYM_pppoe_net_id		1
#define __KSYM_pppoe_xmit		1
#define __KSYM_prandom_u32_state	1
#define __KSYM_put_mtd_device		1
#define __KSYM_rb400_beep		1
#define __KSYM_rb400_spi_get		1
#define __KSYM_rb400_spi_sync		1
#define __KSYM_rb400_spiflash_read_verify	1
#define __KSYM_rb700_change_gpo		1
#define __KSYM_rb_beepled		1
#define __KSYM_rb_change_cfg		1
#define __KSYM_rb_last			1
#define __KSYM_register_ag7100_driver	1
#define __KSYM_register_console		1
#define __KSYM_register_panic_notifier	1
#define __KSYM_register_wifi_gpo	1
#define __KSYM_remap_pfn_range		1
#define __KSYM_rx_handler_hook		1
#define __KSYM_rx_handler_jump		1
#define __KSYM_secure_tcp_seq		1
#define __KSYM_skb_orphan_partial	1
#define __KSYM_skb_recycle		1
#define __KSYM_skb_vlan_untag		1
#define __KSYM_skbuff_head_cache	1
#define __KSYM_spi_async		1
#define __KSYM_static_key_disable	1
#define __KSYM_static_key_enable	1
#define __KSYM_strstr			1
#define __KSYM_system_unbound_wq	1
#define __KSYM_tx_handler_hook		1
#define __KSYM_tx_handler_jump		1
#define __KSYM_unregister_ag7100_driver	1
#define __KSYM_unregister_console	1
#define __KSYM_unregister_panic_notifier	1
#define __KSYM_usb_bulk_msg		1
#define __KSYM_vlan_dev_real_dev	1
#define __KSYM_vprintk			1
#define __KSYM_sock_sendmsg		1
#define __KSYM_contig_page_data		1
#define __KSYM_strcat			1
#define __KSYM_pci_disable_msix		1
#define __KSYM_skb_dump		1
#define __KSYM_pci_find_ext_capability	1
#define __KSYM_pcie_capability_write_word	1
#define __KSYM_dev_set_threaded	1
#define __KSYM_register_switchdev_blocking_notifier	1
#define __KSYM_unregister_switchdev_blocking_notifier	1
#define __KSYM_switchdev_handle_port_obj_add	1
#define __KSYM_switchdev_handle_port_obj_del	1
#define __KSYM_switchdev_handle_port_attr_set	1
#define __KSYM_netlink_add_tap	1
#define __KSYM_netlink_remove_tap	1
#define __KSYM_simple_write_to_buffer	1
#define __KSYM_kstrtoint_from_user	1
#define __KSYM_debugfs_create_u32	1
#define __KSYM_debugfs_create_u8	1
#define __KSYM_debugfs_create_symlink	1
#define __KSYM_debugfs_create_devm_seqfile	1

#ifndef __smips__
#define __KSYM___bitmap_clear		1
#define __KSYM___bitmap_set		1
#define __KSYM___dev_kfree_skb_irq	1
#define __KSYM___fib_lookup		1
#define __KSYM___irq_set_handler	1
#define __KSYM___kernel_write		1
#define __KSYM___kfifo_to_user		1
#define __KSYM___ndelay			1
#define __KSYM___neigh_event_send	1
#define __KSYM___strncpy_from_user_asm	1
#define __KSYM_bitmap_find_next_zero_area_off	1
#define __KSYM_clk_register_fixed_rate	1
#define __KSYM_clkdev_create		1
#define __KSYM_crc_ccitt		1
#define __KSYM_devm_ioremap_resource	1
#define __KSYM_fib_table_lookup		1
#define __KSYM_flush_icache_range	1
#define __KSYM_free_fib_info		1
#define __KSYM_generic_handle_irq	1
#define __KSYM_gpio_request_one		1
#define __KSYM_gpio_request_one		1
#define __KSYM_gpiochip_is_requested	1
#define __KSYM_gpiod_get_raw_value_cansleep	1
#define __KSYM_gpiod_remove_lookup_table	1
#define __KSYM_gpiod_set_raw_value_cansleep	1
#define __KSYM_gpiod_export		1
#define __KSYM_handle_simple_irq	1
#define __KSYM_hci_alloc_dev		1
#define __KSYM_hci_free_dev		1
#define __KSYM_hci_recv_frame		1
#define __KSYM_hci_register_dev		1
#define __KSYM_hci_unregister_dev	1
#define __KSYM_i2c_del_driver		1
#define __KSYM_i2c_new_device		1
#define __KSYM_i2c_register_driver	1
#define __KSYM_i2c_unregister_device	1
#define __KSYM_init_dummy_netdev	1
#define __KSYM_irq_modify_status	1
#define __KSYM_irq_set_chip		1
#define __KSYM_irq_set_chip_data	1
#define __KSYM_irq_set_irq_type		1
#define __KSYM_iterate_dir		1
#define __KSYM_led_set_brightness	1
#define __KSYM_lock_rename		1
#define __KSYM_mfd_add_devices		1
#define __KSYM_mfd_remove_devices	1
#define __KSYM_music_reset_notify	1
#define __KSYM_notify_change		1
#define __KSYM_of_address_to_resource	1
#define __KSYM_of_find_node_by_name	1
#define __KSYM_of_property_read_string_helper	1
#define __KSYM_pci_assign_resource	1
#define __KSYM_pci_dev_present		1
#define __KSYM_pci_ioremap_bar		1
#define __KSYM_pci_release_region	1
#define __KSYM_pci_request_region	1
#define __KSYM_pci_write_config_word	1
#define __KSYM_platform_get_irq		1
#define __KSYM_ptp_clock_register	1
#define __KSYM_ptp_clock_unregister	1
#define __KSYM_rb400_change_cfg		1
#define __KSYM_register_fib_notifier	1
#define __KSYM_register_netevent_notifier	1
#define __KSYM_request_firmware_nowait	1
#define __KSYM_saved_command_line	1
#define __KSYM_spi_busnum_to_master	1
#define __KSYM_spi_new_device		1
#define __KSYM_statfs_by_dentry		1
#define __KSYM_sysfs_update_group	1
#define __KSYM_timecounter_cyc2time	1
#define __KSYM_timecounter_init		1
#define __KSYM_timecounter_read		1
#define __KSYM_unlock_rename		1
#define __KSYM_unregister_fib_notifier	1
#define __KSYM_unregister_netevent_notifier	1
#define __KSYM_vfs_create		1
#define __KSYM_vfs_getattr		1
#define __KSYM_vfs_link			1
#define __KSYM_vfs_mkdir		1
#define __KSYM_vfs_rename		1
#define __KSYM_vfs_rmdir		1
#define __KSYM_vfs_symlink		1
#define __KSYM_vfs_unlink		1
#define __KSYM_virqs			1
#define __KSYM_vm_insert_page		1
#define __KSYM_vsnprintf		1
#endif

#ifdef CONFIG_MIPS_MT
#define __KSYM___wake_up_locked_key	1
#define __KSYM_crypto_register_aead	1
#define __KSYM_crypto_shash_final	1
#define __KSYM_crypto_unregister_aead	1
#define __KSYM_dev_base_lock		1
#define __KSYM_kernel_recvmsg		1
#define __KSYM_memchr			1
#define __KSYM_nsecs_to_jiffies		1
#define __KSYM_pci_find_capability	1
#define __KSYM_pci_write_config_byte	1
#define __KSYM_platform_get_resource	1
#define __KSYM_proc_create		1
#define __KSYM_r4k_dma_cache_wback_inv_fast	1
#define __KSYM_single_open		1
#define __KSYM_single_release		1
#define __KSYM_smp_call_function_single	1
#define __KSYM_smp_call_function_single_async	1
#endif

#ifdef __arm__
#define __KSYM___irq_set_affinity	1
#define __KSYM___machine_arch_type	1
#define __KSYM___pci_reset_function_locked	1
#define __KSYM___spi_alloc_controller	1
#define __KSYM_al_eth_adapter_handle_init	1
#define __KSYM_al_eth_adapter_init	1
#define __KSYM_al_eth_adapter_stop	1
#define __KSYM_al_eth_ctrl_table_def_set	1
#define __KSYM_al_eth_fec_enable	1
#define __KSYM_al_eth_flow_control_config	1
#define __KSYM_al_eth_flr		1
#define __KSYM_al_eth_fsm_table_set	1
#define __KSYM_al_eth_fwd_mac_table_set	1
#define __KSYM_al_eth_fwd_pbits_table_set	1
#define __KSYM_al_eth_fwd_priority_table_set	1
#define __KSYM_al_eth_gearbox_reset	1
#define __KSYM_al_eth_group_lm_init	1
#define __KSYM_al_eth_hash_key_set	1
#define __KSYM_al_eth_link_status_get	1
#define __KSYM_al_eth_mac_config	1
#define __KSYM_al_eth_mac_link_config	1
#define __KSYM_al_eth_mac_start		1
#define __KSYM_al_eth_mac_stats_get	1
#define __KSYM_al_eth_mac_stop		1
#define __KSYM_al_eth_mdio_config	1
#define __KSYM_al_eth_queue_config	1
#define __KSYM_al_eth_rfw_handle_init	1
#define __KSYM_al_eth_rfw_lrss_generic_config	1
#define __KSYM_al_eth_rx_generic_crc_table_init	1
#define __KSYM_al_eth_rx_pkt_limit_config	1
#define __KSYM_al_eth_rx_protocol_detect_table_init	1
#define __KSYM_al_eth_thash_table_set	1
#define __KSYM_al_eth_tx_crc_chksum_replace_cmd_init	1
#define __KSYM_al_eth_tx_generic_crc_table_init	1
#define __KSYM_al_eth_tx_protocol_detect_table_init	1
#define __KSYM_al_serdes_avg_complex_handle_init	1
#define __KSYM_al_serdes_avg_handle_init	1
#define __KSYM_al_serdes_handle_grp_init	1
#define __KSYM_al_serdes_temperature_get_cb_set	1
#define __KSYM_al_udma_iofic_config_ex	1
#define __KSYM_al_udma_iofic_unmask_offset_get_adv	1
#define __KSYM_al_unit_adapter_handle_init	1
#define __KSYM_al_unit_adapter_flr	1
#define __KSYM_crypto_alloc_sync_skcipher	1
#define __KSYM_crypto_authenc_extractkeys	1
#define __KSYM_crypto_dequeue_request	1
#define __KSYM_crypto_enqueue_request	1
#define __KSYM_crypto_init_queue	1
#define __KSYM_crypto_register_aead	1
#define __KSYM_crypto_register_ahash	1
#define __KSYM_crypto_unregister_aead	1
#define __KSYM_crypto_unregister_ahash	1
#define __KSYM_dev_base_lock		1
#define __KSYM_dma_supported		1
#define __KSYM_i2c_transfer		1
#define __KSYM_irq_can_set_affinity	1
#define __KSYM_irq_set_affinity		1
#define __KSYM_irq_set_affinity_hint	1
#define __KSYM_irq_set_irq_type		1
#define __KSYM_kernel_kobj		1
#define __KSYM_of_clk_get_by_name	1
#define __KSYM_of_find_compatible_node	1
#define __KSYM_of_find_matching_node_and_match	1
#define __KSYM_of_iomap			1
#define __KSYM_of_irq_get_byname	1
#define __KSYM_of_mdio_find_bus		1
#define __KSYM_of_property_read_variable_u8_array	1
#define __KSYM_pci_disable_msi		1
#define __KSYM_pci_disable_msix		1
#define __KSYM_sg_nents_for_len		1
#define __KSYM_smp_call_function_single	1
#define __KSYM_smp_call_function_single_async	1
#define __KSYM_spi_register_controller	1
#define __KSYM_sps_alloc_endpoint	1
#define __KSYM_sps_connect		1
#define __KSYM_sps_deregister_bam_device	1
#define __KSYM_sps_disconnect		1
#define __KSYM_sps_free_endpoint	1
#define __KSYM_sps_get_config		1
#define __KSYM_sps_set_config		1
#define __KSYM_sps_register_bam_device	1
#define __KSYM_sps_register_event	1
#define __KSYM_sps_transfer_fast	1
#define __KSYM_sps_transfer_one	        1
#define __KSYM_sps_get_iovec	        1
#define __KSYM_sps_get_unused_desc_num	1
#define __KSYM_sysfs_update_group	1
#define __KSYM_thermal_zone_get_temp	1
#define __KSYM_thermal_zone_get_zone_by_name	1
#define __KSYM_timecounter_cyc2time	1
#define __KSYM_timecounter_init		1
#define __KSYM_timecounter_read		1
#define __KSYM_unregister_fib_notifier	1
#define __KSYM_unregister_netevent_notifier	1
#define __KSYM_v7_dma_flush_range	1
#define __KSYM_v7_dma_flush_range_nosync	1
#define __KSYM_v7_dma_inv_range_nosync	1
#define __KSYM_v7_dma_unmap_area	1
#define __KSYM_al_iofic_mask		1
#define __KSYM_al_iofic_read_mask	1
#define __KSYM_al_iofic_msix_moder_interval_config	1
#define __KSYM_al_iofic_read_cause	1
#define __KSYM_al_iofic_clear_cause	1
#define __KSYM_al_udma_q_handle_get	1
#define __KSYM_al_udma_q_reset		1
#define __KSYM_qcom_smem_state_update_bits		1
#define __KSYM_qcom_smem_state_get		1
#define __KSYM_qcom_smem_alloc		1
#define __KSYM_qcom_smem_get		1
#define __KSYM_regmap_write		1
#define __KSYM_of_get_next_available_child	1
#define __KSYM_devm_reset_controller_register	1
#define __KSYM_of_parse_phandle_with_fixed_args	1
#define __KSYM_syscon_node_to_regmap	1
#define __KSYM_of_device_modalias	1
#define __KSYM_of_clk_set_defaults	1
#define __KSYM_of_device_uevent_modalias 1
#define __KSYM_of_device_request_module 1
#define __KSYM_dw_pcie_prog_outbound_atu 1
#define __KSYM_dw_pcie_link_up		1
#define __KSYM_dw_pcie_wait_for_link	1
#define __KSYM___ktime_divns		1
#define __KSYM_qcom_scm_pas_auth_and_reset      1
#define __KSYM_qcom_register_ssr_notifier	1
#define __KSYM_qcom_unregister_ssr_notifier	1
#define __KSYM_kstrtos8			1
#define __KSYM_cfg80211_find_vendor_elem	1
#define __KSYM_param_get_ushort		1
#define __KSYM_skb_try_coalesce		1
#define __KSYM_kfree_skb_partial	1
#define __KSYM_klist_next		1
#define __KSYM_klist_del		1
#define __KSYM_klist_init		1
#define __KSYM_genl_unlock		1
#define __KSYM_klist_node_attached	1
#define __KSYM_klist_iter_init_node	1
#define __KSYM_klist_add_tail		1
#define __KSYM_tgd_send_gps_pos		1
#define __KSYM_klist_iter_exit		1
#define __KSYM_cfg80211_inform_bss_data	1
#define __KSYM_genl_lock		1
#define __KSYM_rproc_get_by_phandle 1
#define __KSYM_qmi_response_type_v01_ei 1
#define __KSYM_qmi_handle_init 1
#define __KSYM_memremap 1
#define __KSYM_qcom_deregister_ipa_notify 1
#define __KSYM_qmi_send_request 1
#define __KSYM_qmi_txn_wait 1
#define __KSYM_atomic_dec_and_mutex_lock 1
#define __KSYM_build_skb 1
#define __KSYM_qmi_send_response 1
#define __KSYM_qmi_txn_cancel 1
#define __KSYM_qcom_register_ipa_notify 1
#define __KSYM_rproc_put 1
#define __KSYM_memunmap 1
#define __KSYM_qmi_add_server 1
#define __KSYM_qmi_txn_init 1
#define __KSYM_qmi_handle_release 1
#define __KSYM_qmi_send_indication 1
#define __KSYM_qcom_scm_is_available 1
#define __KSYM_qmi_add_lookup 1
#define __KSYM_qcom_mdt_load 1
#define __KSYM_qcom_scm_mem_protect_ipa_region 1
#define __KSYM_qcom_scm_pas_mem_setup 1
#define __KSYM_rfkill_unregister 1
#define __KSYM_rfkill_blocked 1
#define __KSYM_rfkill_destroy 1
#define __KSYM_rfkill_resume_polling 1
#define __KSYM_rfkill_pause_polling 1
#define __KSYM_rfkill_set_hw_state 1
#define __KSYM_rfkill_alloc 1
#define __KSYM_rfkill_register 1
#define __KSYM_rfkill_set_sw_state 1
#define __KSYM_cfg80211_vendor_cmd_reply 1
#endif

#ifdef __aarch64__
#define __KSYM___clean_dcache_area_poc	1
#define __KSYM___clk_get_hw		1
#define __KSYM___dma_unmap_area		1
#define __KSYM___inval_dcache_area	1
#define __KSYM___irq_domain_add		1
#define __KSYM___irq_set_affinity	1
#define __KSYM___request_percpu_irq	1
#define __KSYM___wake_up_locked_key	1
#define __KSYM_add_timer_on		1
#define __KSYM_al_eth_adapter_handle_init	1
#define __KSYM_al_eth_adapter_init	1
#define __KSYM_al_eth_adapter_stop	1
#define __KSYM_al_eth_ctrl_table_def_set	1
#define __KSYM_al_eth_fec_enable	1
#define __KSYM_al_eth_flow_control_config	1
#define __KSYM_al_eth_flr		1
#define __KSYM_al_eth_fsm_table_set	1
#define __KSYM_al_eth_fwd_mac_table_set	1
#define __KSYM_al_eth_fwd_pbits_table_set	1
#define __KSYM_al_eth_fwd_priority_table_set	1
#define __KSYM_al_eth_gearbox_reset	1
#define __KSYM_al_eth_group_lm_init	1
#define __KSYM_al_eth_hash_key_set	1
#define __KSYM_al_eth_link_status_get	1
#define __KSYM_al_eth_mac_config	1
#define __KSYM_al_eth_mac_link_config	1
#define __KSYM_al_eth_mac_start		1
#define __KSYM_al_eth_mac_stats_get	1
#define __KSYM_al_eth_mac_stop		1
#define __KSYM_al_eth_mdio_config	1
#define __KSYM_al_eth_queue_config	1
#define __KSYM_al_eth_rfw_handle_init	1
#define __KSYM_al_eth_rfw_lrss_generic_config	1
#define __KSYM_al_eth_rx_generic_crc_table_init	1
#define __KSYM_al_eth_rx_pkt_limit_config	1
#define __KSYM_al_eth_rx_protocol_detect_table_init	1
#define __KSYM_al_eth_thash_table_set	1
#define __KSYM_al_eth_tx_crc_chksum_replace_cmd_init	1
#define __KSYM_al_eth_tx_generic_crc_table_init	1
#define __KSYM_al_eth_tx_protocol_detect_table_init	1
#define __KSYM_al_iofic_mask		1
#define __KSYM_al_iofic_read_mask	1
#define __KSYM_al_iofic_read_cause	1
#define __KSYM_al_iofic_clear_cause	1
#define __KSYM_al_iofic_msix_moder_interval_config	1
#define __KSYM_al_serdes_avg_complex_handle_init	1
#define __KSYM_al_serdes_avg_handle_init	1
#define __KSYM_al_serdes_handle_grp_init	1
#define __KSYM_al_serdes_temperature_get_cb_set	1
#define __KSYM_al_udma_iofic_config_ex	1
#define __KSYM_al_udma_iofic_unmask_offset_get_adv	1
#define __KSYM_al_udma_q_handle_get	1
#define __KSYM_al_udma_q_reset		1
#define __KSYM_al_udma_q_init		1
#define __KSYM_al_udma_q_enable		1
#define __KSYM_al_unit_adapter_handle_init	1
#define __KSYM_al_unit_adapter_flr	1
#define __KSYM_cache_line_size		1
#define __KSYM_clk_hw_is_prepared	1
#define __KSYM_clk_register		1
#define __KSYM_clk_set_parent		1
#define __KSYM_crypto_shash_final	1
#define __KSYM_dev_base_lock		1
#define __KSYM_disable_percpu_irq	1
#define __KSYM_enable_percpu_irq	1
#define __KSYM_free_percpu_irq		1
#define __KSYM_fwnode_device_is_available	1
#define __KSYM_fwnode_get_next_child_node	1
#define __KSYM_fwnode_property_read_u32_array	1
#define __KSYM_i2c_transfer		1
#define __KSYM_irq_dispose_mapping	1
#define __KSYM_irq_domain_xlate_onecell	1
#define __KSYM_irq_find_mapping		1
#define __KSYM_irq_get_irq_data		1
#define __KSYM_irq_set_affinity_hint	1
#define __KSYM_irq_set_irq_type		1
#define __KSYM_kernel_kobj		1
#define __KSYM_kmalloc_order		1
#define __KSYM_memremap			1
#define __KSYM_of_clk_get_by_name	1
#define __KSYM_of_dma_configure		1
#define __KSYM_of_find_compatible_node	1
#define __KSYM_of_find_matching_node_and_match	1
#define __KSYM_of_find_node_opts_by_path	1
#define __KSYM_of_gen_pool_get		1
#define __KSYM_of_get_phy_mode		1
#define __KSYM_of_iomap			1
#define __KSYM_of_irq_get		1
#define __KSYM_of_irq_get_byname	1
#define __KSYM_of_property_read_variable_u8_array	1
#define __KSYM_of_reserved_mem_device_init_by_idx	1
#define __KSYM_pci_clear_master		1
#define __KSYM_pci_disable_msi		1
#define __KSYM_pci_enable_wake		1
#define __KSYM_pci_iomap		1
#define __KSYM_pci_release_regions	1
#define __KSYM_pci_request_regions	1
#define __KSYM___pci_reset_function_locked	1
#define __KSYM_pci_sriov_get_totalvfs	1
#define __KSYM_phy_ethtool_ksettings_set	1
#define __KSYM_regmap_read		1
#define __KSYM_regmap_write		1
#define __KSYM_smp_call_function_single	1
#define __KSYM_smp_call_function_single_async	1
#define __KSYM_syscon_regmap_lookup_by_phandle	1
#define __KSYM_thermal_zone_get_temp	1
#define __KSYM_thermal_zone_get_zone_by_name	1
#define __KSYM___dma_flush_area		1
#define __KSYM__q6v5_wdog_interrupt	1
#define __KSYM__q6v5_ready_interrupt	1
#define __KSYM__q6v5_fatal_interrupt	1
#define __KSYM__q6v5_panic_handler	1
#define __KSYM__subsys_get_crash_status	1
#define __KSYM__create_ramdump_device_file	1
#define __KSYM_al_pcie_atu_region_set	1
#define __KSYM_al_pcie_msix_config	1
#define __KSYM_al_pcie_pf_handle_init	1
#define __KSYM_al_pcie_pf_config	1
#define __KSYM_al_pcie_port_handle_init	1
#define __KSYM_al_pcie_port_config	1
#define __KSYM_al_addr_map_pasw_set	1
#define __KSYM_al_pcie_app_req_retry_set	1
#define __KSYM_al_pcie_local_cfg_space_write	1
#define __KSYM_al_pcie_local_cfg_space_read	1
#define __KSYM_al_pcie_msi_int_gen	1
#define __KSYM_al_pcie_legacy_int_gen	1
#define __KSYM_al_pcie_port_max_num_of_pfs_set	1
#define __KSYM_al_pcie_port_perf_params_print	1
#define __KSYM_al_init_pcie	1
#define __KSYM_udma_fast_memcpy	1
#define __KSYM_al_ssm_dma_action	1
#define __KSYM_al_udma_cdesc_packet_get	1
#define __KSYM_pci_enable_sriov	1
#define __KSYM_pci_disable_sriov	1
/* Alpine v3 thermal */
#define __KSYM_al_vt_sensor_handle_init	1
#define __KSYM_al_vt_sensor_readout_is_valid	1
#define __KSYM_al_sbus_handle_init	1
#define __KSYM_thermal_zone_of_sensor_register	1
#define __KSYM_al_vt_sensor_readout_get	1
#define __KSYM_al_vt_sensor_enable_set	1
#define __KSYM_al_vt_sensor_trigger_continuous	1
#define __KSYM_thermal_zone_of_sensor_unregister	1
#endif

#if defined(__arm__) || defined(__aarch64__)
/* wireless stuff */
#define __KSYM_vmap			1
#define __KSYM_vunmap			1
#define __KSYM_of_get_address		1
#define __KSYM___devm_release_region	1
#define __KSYM___hrtimer_get_remaining	1
#define __KSYM___memcpy_toio		1
#define __KSYM___memset_io		1
#define __KSYM___reset_control_get	1
#define __KSYM__raw_read_lock_irqsave	1
#define __KSYM__raw_read_unlock_irqrestore	1
#define __KSYM__raw_write_lock_irqsave	1
#define __KSYM__raw_write_unlock_irqrestore	1
#define __KSYM_atomic_notifier_chain_register	1
#define __KSYM_atomic_notifier_chain_unregister	1
#define __KSYM_clk_get			1
#define __KSYM_cnss_dump_qmi_history	1
#define __KSYM_cnss_get_fw_files_for_target	1
#define __KSYM_cnss_get_msi_address	1
#define __KSYM_cnss_get_msi_irq		1
#define __KSYM_cnss_get_pci_dev_by_device_id	1
#define __KSYM_cnss_get_platform_cap	1
#define __KSYM_cnss_get_soc_info	1
#define __KSYM_cnss_is_cold_boot_cal_done	1
#define __KSYM_cnss_is_fw_ready		1
#define __KSYM_cnss_pci_link_down	1
#define __KSYM_cnss_pcie_remove_bus	1
#define __KSYM_cnss_pcie_rescan		1
#define __KSYM_cnss_power_off_device	1
#define __KSYM_cnss_power_on_device	1
#define __KSYM_cnss_schedule_recovery	1
#define __KSYM_cnss_self_recovery	1
#define __KSYM_cnss_subsystem_get	1
#define __KSYM_cnss_subsystem_put	1
#define __KSYM_cnss_wlan_disable	1
#define __KSYM_cnss_wlan_enable		1
#define __KSYM_cnss_wlan_register_driver	1
#define __KSYM_cnss_wlan_unregister_driver	1
#define __KSYM_devm_iounmap		1
#define __KSYM_disable_irq_nosync	1
#define __KSYM_dma_get_sgtable_attrs	1
#define __KSYM_do_exit			1
#define __KSYM_down			1
#define __KSYM_down_timeout		1
#define __KSYM_filp_close		1
#define __KSYM_jiffies_to_timespec64	1
#define __KSYM_jiffies_to_usecs		1
#define __KSYM_mmiocpy			1
#define __KSYM_mmioset			1
#define __KSYM_of_n_addr_cells		1
#define __KSYM_of_n_size_cells		1
#define __KSYM_panic_notifier_list	1
#define __KSYM_qca6290_support		1
#define __KSYM_relay_buf_full		1
#define __KSYM_relay_close		1
#define __KSYM_relay_flush		1
#define __KSYM_relay_open		1
#define __KSYM_relay_reset		1
#define __KSYM_relay_subbufs_consumed	1
#define __KSYM_relay_switch_subbuf	1
#define __KSYM_rtc_time64_to_tm		1
#define __KSYM_save_stack_trace_tsk	1
#define __KSYM_sched_clock		1
#define __KSYM_seq_hex_dump		1
#define __KSYM_seq_vprintf		1
#define __KSYM_seq_write		1
#define __KSYM_set_cpus_allowed_ptr	1
#define __KSYM_set_user_nice		1
#define __KSYM_sprint_symbol		1
#define __KSYM_stack_trace_print	1
#define __KSYM_cfg80211_vendor_cmd_reply 1
#define __KSYM___cfg80211_alloc_event_skb 1
#define __KSYM___cfg80211_send_event_skb 1
#define __KSYM_cfg80211_disconnected 1
#define __KSYM_cfg80211_roamed 1
#define __KSYM_cfg80211_connect_done 1
#define __KSYM_cfg80211_ft_event 1
#define __KSYM___cfg80211_alloc_reply_skb 1
#define __KSYM_cfg80211_external_auth_request 1
#define __KSYM_cnss_set_ramdump_enabled 1
#define __KSYM_cnss_get_user_msi_assignment     1
#define __KSYM_cnss_get_pci_dev_id_from_plat_dev        1
#define __KSYM_cnss_is_dev_initialized  1
#define __KSYM_cnss_get_pci_dev_from_plat_dev   1
#define __KSYM_os_if_spectral_free_skb  1
#define __KSYM___wbuf_unmap_single      1
#define __KSYM___wbuf_map_single        1
#define __KSYM_utils_dfs_init_nol       1
#define __KSYM_qdf_nbuf_tx_desc_count_update    1
#define __KSYM_ieee80211_chan2freq      1
#define __KSYM_relay_file_operations	1
#define __KSYM_dw_spi_cs_lock		1
#define __KSYM_dw_spi_cs_unlock		1
#define __KSYM_cnss_athdiag_read	1
#define __KSYM_cnss_athdiag_write	1
#define __KSYM_cnss_get_q6_time		1
#define __KSYM_cnss_wait_for_cold_boot_cal_done	1
#define __KSYM_cnss_wait_for_fw_ready	1
#define __KSYM__wlfw_antenna_switch_resp_msg_v01_ei	1
#define __KSYM__wlfw_antenna_switch_req_msg_v01_ei	1
#define __KSYM__wlfw_antenna_grant_resp_msg_v01_ei	1
#define __KSYM__wlfw_antenna_grant_req_msg_v01_ei	1
#define __KSYM__wlfw_m3_dump_upload_done_resp_msg_v01_ei	1
#define __KSYM__wlfw_m3_dump_upload_done_req_msg_v01_ei	1
#define __KSYM__wlfw_m3_dump_upload_req_ind_msg_v01_ei	1
#define __KSYM__qcom_scm_wcss_boot	1
#define __KSYM_netdev_alloc_frag	1
#define __KSYM_skb_coalesce_rx_frag	1
#define __KSYM_skb_coalesce_rx_frag	1
#define __KSYM_cnss_get_ramdump_device_name	1
#define __KSYM_cnss_set_recovery_enabled	1
#define __KSYM_cnss_set_driver_mode	1
#define __KSYM_cnss_get_driver_mode	1
#define __KSYM_firmware_request_nowarn	1
#define __KSYM_of_get_i2c_adapter_by_node	1
#endif

#if defined(__mips__) || defined(__arm__) || defined(__aarch64__)
#ifndef __smips__
/* sybols needed for prestera_8250 */
#define __KSYM_of_alias_get_id	1
#define __KSYM_of_device_is_big_endian	1
#define __KSYM_dw8250_setup_port	1
#define __KSYM_serial8250_clear_and_reinit_fifos	1
#define __KSYM_serial8250_do_pm	1
#define __KSYM_serial8250_do_set_ldisc	1
#define __KSYM_serial8250_do_set_termios	1
#define __KSYM_serial8250_handle_irq	1
#define __KSYM_serial8250_register_8250_port	1
#define __KSYM_serial8250_unregister_port	1
#define __KSYM___devm_reset_control_get	1
#define __KSYM_clk_get_rate	1
#define __KSYM_clk_round_rate	1
#define __KSYM_clk_set_rate	1
#define __KSYM_devm_clk_get_optional	1
#define __KSYM_ioread32be	1
#define __KSYM_iowrite32be	1
#define __KSYM_platform_get_resource_byname	1
#define __KSYM_reset_control_assert	1
#define __KSYM_reset_control_deassert	1
#endif
#endif

#ifdef __powerpc__
#define __KSYM___alloc_pages_nodemask	1
#define __KSYM___devm_release_region	1
#define __KSYM___devm_request_region	1
#define __KSYM___free_pages		1
#define __KSYM___irq_set_affinity	1
#define __KSYM___mfdcr			1
#define __KSYM___mtdcr			1
#define __KSYM___wake_up_locked_key	1
#define __KSYM__memcpy_fromio		1
#define __KSYM__memset_io		1
#define __KSYM_bman_acquire		1
#define __KSYM_bman_free_pool		1
#define __KSYM_bman_get_params		1
#define __KSYM_bman_new_pool		1
#define __KSYM_bman_release		1
#define __KSYM_bus_register_notifier	1
#define __KSYM_bus_unregister_notifier	1
#define __KSYM_cdev_add			1
#define __KSYM_change_latch		1
#define __KSYM_cur_cpu_spec		1
#define __KSYM_dcr_resource_start	1
#define __KSYM_dev_base_lock		1
#define __KSYM_dev_mc_add_global	1
#define __KSYM_dev_set_threaded		1
#define __KSYM_devm_free_irq		1
#define __KSYM_devm_iounmap		1
#define __KSYM_devres_add		1
#define __KSYM_devres_alloc_node	1
#define __KSYM_devres_free		1
#define __KSYM_dma_set_coherent_mask	1
#define __KSYM_down_interruptible	1
#define __KSYM_ethtool_convert_link_mode_to_legacy_u32	1
#define __KSYM_get_gpio_def		1
#define __KSYM_get_virq_nr		1
#define __KSYM_ioremap			1
#define __KSYM_ioremap_prot		1
#define __KSYM_irq_create_mapping	1
#define __KSYM_irq_dispose_mapping	1
#define __KSYM_irq_find_matching_fwspec	1
#define __KSYM_irq_set_irq_type		1
#define __KSYM_kernel_kobj		1
#define __KSYM_kernel_read		1
#define __KSYM_kernel_recvmsg		1
#define __KSYM_kernel_sendmsg		1
#define __KSYM_led_trigger_register	1
#define __KSYM_led_trigger_unregister	1
#define __KSYM_localbus_lock		1
#define __KSYM_lookup_one_len		1
#define __KSYM_machine_id		1
#define __KSYM_mdiobus_alloc_size	1
#define __KSYM_mdiobus_alloc_size	1
#define __KSYM_mdiobus_free		1
#define __KSYM_mdiobus_free		1
#define __KSYM_mdiobus_unregister	1
#define __KSYM_mdiobus_unregister	1
#define __KSYM_memchr			1
#define __KSYM_mii_check_link		1
#define __KSYM_misc_deregister		1
#define __KSYM_misc_register		1
#define __KSYM_nsecs_to_jiffies		1
#define __KSYM_of_dev_put		1
#define __KSYM_of_device_is_available	1
#define __KSYM_of_find_all_nodes	1
#define __KSYM_of_find_device_by_node	1
#define __KSYM_of_find_matching_node_and_match	1
#define __KSYM_of_find_node_by_phandle	1
#define __KSYM_of_find_node_by_type	1
#define __KSYM_of_find_node_opts_by_path	1
#define __KSYM_of_get_address		1
#define __KSYM_of_get_mac_address	1
#define __KSYM_of_get_mac_address	1
#define __KSYM_of_get_parent		1
#define __KSYM_of_irq_to_resource	1
#define __KSYM_of_match_node		1
#define __KSYM_of_mdiobus_register	1
#define __KSYM_of_mdiobus_register	1
#define __KSYM_of_n_addr_cells		1
#define __KSYM_of_n_size_cells		1
#define __KSYM_of_node_get		1
#define __KSYM_of_translate_address	1
#define __KSYM_param_ops_byte		1
#define __KSYM_pci_disable_msi		1
#define __KSYM_pci_enable_device_mem	1
#define __KSYM_pci_enable_msi		1
#define __KSYM_pci_enable_wake		1
#define __KSYM_phy_attach		1
#define __KSYM_phy_disconnect		1
#define __KSYM_phy_start		1
#define __KSYM_phy_start_aneg		1
#define __KSYM_phy_stop			1
#define __KSYM_ppc_proc_freq		1
#define __KSYM_ppc_tb_freq		1
#define __KSYM_qman_affine_channel	1
#define __KSYM_qman_affine_cpus		1
#define __KSYM_qman_alloc_cgrid_range	1
#define __KSYM_qman_alloc_pool_range	1
#define __KSYM_qman_create_cgr		1
#define __KSYM_qman_create_fq		1
#define __KSYM_qman_delete_cgr		1
#define __KSYM_qman_destroy_fq		1
#define __KSYM_qman_enqueue		1
#define __KSYM_qman_fq_fqid		1
#define __KSYM_qman_init_fq		1
#define __KSYM_qman_irqsource_add	1
#define __KSYM_qman_irqsource_remove	1
#define __KSYM_qman_oos_fq		1
#define __KSYM_qman_poll_dqrr		1
#define __KSYM_qman_release_cgrid_range	1
#define __KSYM_qman_retire_fq		1
#define __KSYM_qman_static_dequeue_add	1
#define __KSYM_release_firmware		1
#define __KSYM_request_firmware		1
#define __KSYM_router_beep		1
#define __KSYM_set_cpus_allowed_ptr	1
#define __KSYM_skb_recycle_check	1
#define __KSYM_smp_call_function_single	1
#define __KSYM_smp_call_function_single_async	1
#define __KSYM_smp_hw_index		1
#define __KSYM_sockfd_lookup		1
#define __KSYM_strcasecmp		1
#define __KSYM_strncpy_from_user	1
#define __KSYM_strpbrk			1
#define __KSYM_strspn			1
#define __KSYM_switch_monitor		1
#define __KSYM_synchronize_irq		1
#define __KSYM_tb_ticks_per_jiffy	1
#define __KSYM_timebase_read		1
#define __KSYM_up			1
#define __KSYM_vfs_fsync		1
#define __KSYM_virq_host		1
#define __KSYM_vm_yield			1
#define __KSYM_vsscanf			1
#endif
