/*
 * Copyright 2018, Amazon.com, Inc. or its affiliates. All Rights Reserved
 */

/**
 *  @{
 * @file   al_hal_iofic_x2_regs.h
 *
 * @brief iofic_x2 registers
 *
 * This file was auto-generated by RegGen v1.3.3
 *
 */

#ifndef __AL_HAL_IOFIC_X2_REGS_H__
#define __AL_HAL_IOFIC_X2_REGS_H__

#include "al_hal_common.h"

#include "al_hal_iofic_grp_ctrl_regs.h"

#ifdef __cplusplus
extern "C" {
#endif

/**************************************************************************************************
 * al_iofic_x2_regs
 **************************************************************************************************/
struct al_iofic_x2_regs {
	/* [0x0] */
	struct al_iofic_grp_ctrl_regs ctrl[2];
};

/* Asserts */
al_static_assert(sizeof(struct al_iofic_grp_ctrl_regs) == 64,
	"Expected other registers struct size!");

#ifdef __cplusplus
}
#endif

#endif

/** @} */
