KBUILD_CFLAGS += -DAL_DEV_ID_ALPINE_V1=0
KBUILD_CFLAGS += -DAL_DEV_ID_ALPINE_V2=1
KBUILD_CFLAGS += -DAL_DEV_ID_ALPINE_V3=2
KBUILD_CFLAGS += -DAL_DEV_ID_ALPINE_V4=3


KBUILD_CFLAGS += $(HAL_PLATFORM_INCLUDE_PATH_ALPINE_V2)
KBUILD_CFLAGS += $(HAL_PLATFORM_INCLUDE_PATH_ALPINE_V3)

HAL_TOP=$(srctree)/drivers/soc/alpine/HAL
include $(HAL_TOP)/file_list.mk

KBUILD_CFLAGS += -I$(srctree)/drivers/soc/alpine
KBUILD_CFLAGS += -I$(srctree)/include/soc/alpine

KBUILD_CFLAGS += $(HAL_USER_INCLUDE_PATH)
KBUILD_CFLAGS += $(HAL_DRIVER_INCLUDE_PATH)
KBUILD_CFLAGS += $(HAL_INIT_INCLUDE_PATH)
